version: '3.4'

services:
  api-gerenciar-funcionarios:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=db-gerenciar-funcionarios;Port=5432;Database=funcionarios_db;Username=postgres;Password=postgres
    ports:
      - "57751:8080"
      - "57752:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro